# Generated by Django 3.1.3 on 2020-11-20 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow_Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal_Number', models.IntegerField(unique=True)),
                ('Group_Name', models.TextField(max_length=60)),
                ('Date_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Previous_Area', models.TextField(max_length=50)),
                ('Time_Area', models.TimeField(default=django.utils.timezone.now)),
                ('Device_Name', models.TextField(max_length=40, unique=True)),
                ('Resutls', models.CharField(max_length=150, unique=True)),
                ('Gate_Decision', models.CharField(max_length=100)),
                ('Milking_Interval', models.IntegerField()),
                ('Incompletely_Milked_Teats', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Djurnr', models.IntegerField(unique=True)),
                ('Grupp', models.CharField(max_length=150)),
                ('Händelsedatum', models.DateField(default=django.utils.timezone.now)),
                ('Typ', models.CharField(max_length=30)),
                ('Beskrivning', models.CharField(max_length=100)),
                ('Utgångsdatum', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feed_Day_Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal_Id', models.IntegerField(unique=True)),
                ('Observation_day', models.DateField(default=django.utils.timezone.now)),
                ('Feed_quantity', models.IntegerField(max_length=10)),
                ('Feed_number', models.IntegerField(null=True)),
                ('Equipment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GigaCow_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Official_Reg_No', models.CharField(max_length=30, unique=True)),
                ('Average_Activity_Last_24h', models.IntegerField()),
                ('Relative_Activity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('High_Activity_Start_Hour', models.IntegerField()),
                ('High_Activity_Level', models.IntegerField()),
                ('General_High_Probability', models.IntegerField()),
                ('Gate_Decision', models.CharField(max_length=100)),
                ('High_Activity_Time_Last_48h', models.IntegerField()),
                ('Hours_Since_Sending_Activity', models.IntegerField(null=True)),
                ('High_Activity_Today', models.CharField(max_length=20)),
                ('High_Activity_Yesterday', models.CharField(max_length=10)),
                ('Low_Activity', models.CharField(max_length=20)),
                ('General_Low_Probability', models.IntegerField(max_length=4, null=True)),
                ('Hours_Since_High_Activity', models.IntegerField(max_length=4, null=True)),
            ],
        ),
    ]
